name: data_class_example
description: Example for DataClass.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  data_class:
    path: ../data_class/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.7.4
  data_class_generator:
    path: ../data_class_generator/


flutter:
  uses-material-design: true