name: data_class_annotation
description: This library provides the @dataClass annotation, used to generate code via the data_class_annotation_generator package.
version: 0.1.8
homepage: https://github.com/Ltei/data_class

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  collection: ^1.14.13
