name: data_class_annotation_generator
description: Automatically generate equals, hashCode, toString and copyWith methods for @dataClass annotated classes.
version: 0.1.3
homepage: https://github.com/Ltei/data_class

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  source_gen: ^0.9.4+7
  code_builder: ^3.2.1
  data_class_annotation: ^0.1.2

  analyzer: ^0.39.0
  build: '^1.2.2'
  build_config: '>=0.2.6 <0.5.0'
  meta: ^1.1.0

dev_dependencies:
  build_test: ^0.10.12
  test: ^1.11.0
