name: data_class_annotation_generator
description: Automatically generate equals, hashCode, toString and copyWith methods for @dataClass annotated classes.
version: 0.1.5
homepage: https://github.com/Ltei/data_class

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  source_gen: ^0.9.6
  code_builder: ^3.4.1
#  data_class_annotation: ^0.1.5
  data_class_annotation:
    path: ../data_class_annotation/

  analyzer: ^0.39.14
  build: ^1.3.0
  build_config: ^0.4.2
  meta: ^1.1.0

dev_dependencies:
  build_test: ^0.10.12
  test: ^1.15.4
