name: data_class_annotation_generator
description: Automatically generate equals, hashCode, toString and copyWith methods for @dataClass annotated classes.
version: 0.1.9
homepage: https://github.com/Ltei/data_class

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  analyzer: '>=0.39.0 <0.41.0'
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <0.5.0'

  meta: ^1.1.0
  source_gen: ^0.9.6
  code_builder: ^3.4.1

  data_class_annotation: ^0.1.8
