name: data_class
description: Data class for Dart.
version: 0.1.0
author: Ltei <xavier.peltier@outlook.com>
homepage: https://github.com/Ltei/data_class

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: 1.3.4
